name: "Maintainerr"
slug: "maintainerr"
version: "0.1.0"
description: >
  Maintenance tool for the Plex ecosystem
url: "https://github.com/Maintainerr/Maintainerr"

arch:
  - amd64

startup: application
boot: auto

ports:
  "6246/tcp": 6246
ports_description:
  "6246/tcp": "Maintainerr web interface"

webui: "http://[HOST]:[PORT:6246]/"
watchdog: "tcp://[HOST]:[PORT:6246]"

# Only env Maintainerr really cares about here is TZ
environment:
  TZ: "America/New_York"

# We’re building a custom image from the Dockerfile in this folder.
# The actual image name HA uses will be something like:
# <machine-id>/amd64-addon-maintainerr:0.1.0
# This line is optional, but harmless if you leave it like this.
image: "local/maintainerr-addon"

# Important: this is NOT a “generic container” anymore
legacy: false
