name: "Maintainerr"
slug: "maintainerr"
version: "0.1.12"
description: "Maintenance tool for the Plex ecosystem"
url: "https://github.com/Maintainerr/Maintainerr"

arch:
  - amd64
  - aarch64

startup: services
boot: auto

ports:
  "6246/tcp": 6246
ports_description:
  "6246/tcp": "Maintainerr web interface"

webui: "http://[HOST]:[PORT:6246]/"

host_network: true

backup: hot
